# Generated by Django 5.2.4 on 2025-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='delivery_status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='processing', max_length=50),
        ),
    ]
