# Generated by Django 5.2.4 on 2025-08-05 08:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+996', max_length=128, region=None, unique=True),
        ),
    ]
